"""Local streaming-service aliases kept separate from upstream mappings.

Keeping local aliases in their own module makes upstream ``region.py`` merges
safe: upstream can reorder or extend its service catalogue without repeatedly
conflicting with these project-specific additions.
"""

CUSTOM_STREAMING_SERVICES = {
    # Movies Anywhere is also abbreviated as YKW in some release names.
    "YKW": "MA",

    # Indian and South Asian streaming services
    "Prime Video": "AMZN",
    "Amazon Prime Video": "AMZN",
    "Sun NXT": "SNXT",
    "SunNXT": "SNXT",
    "SNXT": "SNXT",
    "Tentkotta": "TK",
    "TK": "TK",
    "Sony LIV": "SONY",
    "SonyLIV": "SONY",
    "Google Play": "GPLAY",
    "GooglePlay": "GPLAY",
    "GPLAY": "GPLAY",
    "Voot Select": "VOOT",
    "Voot": "VOOT",
    "VOOT": "VOOT",
    "Disney Plus Hotstar": "DSPH",
    "Disney+ Hotstar": "DSPH",
    "DisneyPlusHotstar": "DSPH",
    "DSPH": "DSPH",
    "JioHotstar": "JHS",
    "Jio Hotstar": "JHS",
    "JHS": "JHS",
    "Zee5": "ZEE5",
    "ZEE5": "ZEE5",
    "ZEE 5": "ZEE5",
    "Jio Cinema": "JC",
    "JioCinema": "JC",
    "JC": "JC",
    "Simply South": "SS",
    "SimplySouth": "SS",
    "SS": "SS",
    "AHA": "AHA",
    "Aha": "AHA",
    "MX Player": "MX",
    "MXPlayer": "MX",
    "MX": "MX",
    "Hungama Play": "HPLAY",
    "HungamaPlay": "HPLAY",
    "Hungama": "HPLAY",
    "HPLAY": "HPLAY",
    "TVF Play": "TVF",
    "TVFPlay": "TVF",
    "TVF": "TVF",
    "Shemaroo Me": "SME",
    "ShemarooMe": "SME",
    "Shemaroo me": "SME",
    "SME": "SME",
    "ALT Balaji": "ALT",
    "AltBalaji": "ALT",
    "Alt Balaji": "ALT",
    "ALT": "ALT",
    "Lionsgate Play": "LGP",
    "LionsgatePlay": "LGP",
    "LGP": "LGP",
    "Book My Show": "BMS",
    "BookMyShow": "BMS",
    "BMS": "BMS",
    "Chaupal TV": "CHTV",
    "Chaupal": "CHTV",
    "ChaupalTV": "CHTV",
    "CHTV": "CHTV",
    "ManoramaMAX": "MMAX",
    "Manorama MAX": "MMAX",
    "ManoramaMax": "MMAX",
    "MMAX": "MMAX",
    "Sainaplay": "SPLAY",
    "Saina Play": "SPLAY",
    "SainaPlay": "SPLAY",
    "SPLAY": "SPLAY",
    "Discovery+": "DSCV",
    "DSCV": "DSCV",
    "chorki": "CRKI",
}
